# .readthedocs.yaml
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    # These jobs run before the main build job
    pre_build:
      # Select the correct mkdocs config file based on the language
      - |
        if [ "$READTHEDOCS_LANGUAGE" = "zh-cn" ]; then
          echo "Building Chinese (zh-cn) docs"
          cp mkdocs_zh.yml mkdocs.yml
        else
          echo "Building English (en) docs"
          cp mkdocs_en.yml mkdocs.yml
        fi

# Tell Read the Docs to build your documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt
