
site_name: "IoT 设备使用手册"
site_url: "https://laosong-IMF.github.io/wthm_dosc/" # 请替换成您的 URL

theme:
  name: readthedocs
  language: zh

nav:
  - 首页: index.md
  - 产品技术参数: product-specs.md
  - Wi-Fi配网说明: wifi-setup.md

plugins:
  - search
